<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE components [

<!ELEMENT components ( (description)* | (component)*) >
<!ELEMENT description ANY>

<!ELEMENT component ( (panel)* | (library)* | (dependency)* |(description)?| (requirement)* )>
<!ATTLIST component
    name ID #REQUIRED
    desc CDATA #REQUIRED
>

<!ELEMENT panel ( (description)? | (link)? | (picture)? |(button)? )>
<!ATTLIST panel
    name CDATA #REQUIRED
    fname CDATA #REQUIRED
    fullname CDATA #REQUIRED
>

<!ELEMENT dependency ANY>
<!ELEMENT requirement ANY>

<!ELEMENT library ( (link)? )>
<!ATTLIST library
    name CDATA #REQUIRED
>

<!ELEMENT link ANY>
<!ATTLIST link
    url CDATA #REQUIRED
    text CDATA #REQUIRED
>


<!ELEMENT button ANY>
<!ATTLIST button
    text CDATA #REQUIRED
>

<!ELEMENT picture ANY>
<!ATTLIST image
    id  CDATA #REQUIRED
    url CDATA #REQUIRED
    caption CDATA #IMPLIED
>



]>


<!-- by defining xmlns:html... we allow the use of html tags
in form of e.g
    <html:b> ...  </html:b>,  <html:i> ... </html:i>
in the whole document.
Then, they need to be translated appropriately in xslt.
See the rule on the top of wycieczka.xsl for appropriate rule
-->

<components xmlns:html="http://www.w3.org/1999/xhtml">

<description> 
<html:p>
This is a JCOP Framework documentation of the panels <html:br/>

<html:a href='http://cern.ch/itcobe'> IT CO/BE webpage</html:a> 
<html:br/>
</html:p>
</description>

<component name="fwConfigurationDB" desc="Configuration Database Tool">
    <dependency> fwCore </dependency>
    <requirement> Oracle client </requirement>
    <requirement> CtrlRDBAccess >= 0.45 </requirement>

    <description>
	<html:p> The ConfigurationDB tool is used to store versions of static and dynamic
	configuration data for PVSS (Framework and non-Framework) devices in the Oracle
	database, and to configure the systems (apply settings) using the configuration
	data stored there.
	</html:p>
	<html:p> A "getting-started" guide for the use of the fwConfigurationDB libraries
	is available at the 
	<link url="scripts/libs/index.html" text="main library help page"/>.
	</html:p>
    </description>    
    <library name="Global help with all functions in the component library"> <link url="scripts/libs/index.html" text="All functions in fwConfigurationDB"/></library>
    <library name="Main functions"> <link url="scripts/libs/a00003.html" text="fwConfigurationDB.ctl"/></library>
    <library name="Functions related to database access"> <link url="scripts/libs/a00004.html" text="fwConfigurationDB_DBAccess.ctl"/></library>
    <library name="Device configuration functions"> <link url="scripts/libs/a00006.html" text="fwConfigurationDB_DeviceConfiguration.ctl"/></library>
    <library name="Functions related to device hierarhies"> <link url="scripts/libs/a00008.html" text="fwConfigurationDB_Hierarchies.ctl"/></library>
    <library name="Functions related to recipes"> <link url="scripts/libs/a00009.html" text="fwConfigurationDB_Recipes.ctl"/></library>
    <library name="Various setup functions"> <link url="scripts/libs/a000010.html" text="fwConfigurationDB_Setup.ctl"/></library>
    <library name="Auxiliary utility functions"> <link url="scripts/libs/a00012.html" text="fwConfigurationDB_Utils.ctl"/></library>

<panel name="fwConfigurationDB.pnl" fname="fwConfigurationDB" fullname="Main Configuration Database panel">
    <link url='fwConfigurationDB_Setup.html' text='Setup panel'> </link>
    <description>    
	The main CDB Panel
    </description>
    <picture id="1" url='fwConfigurationDB.png' caption='The panel in state where no DB connection is configured'/>
    <picture id="2" url='fwConfigurationDB_B1.png' caption=''/>
    <picture id="3" url='fwConfigurationDB_B2.png' caption=''/>
</panel>


<panel name="fwConfigurationDB_Setup.pnl" fname="fwConfigurationDB_Setup" fullname="Setup panel">
    <picture id="1" url='fwConfigurationDB_Setup.png' caption=''/>
    <picture id="2" url='fwConfigurationDB_Setup2.png' caption=''/>
    <picture id="3" url='fwConfigurationDB_Setup3.png' caption=''/>
    <picture id="4" url='fwConfigurationDB_Setup5.png' caption=''/>
</panel>

<panel name="fwConfigurationDB_Advanced.pnl" fname="fwConfigurationDB_Advanced" fullname="Advanced operations panel">
    <picture id="1" url='fwConfigurationDB_Advanced.png' caption='Advanced operations panel'/>
</panel>

<panel name="fwConfigurationDB_RecipeManage.pnl" fname="fwConfigurationDB_RecipeManage" fullname="Manage recipes panel">
    <picture id="1" url='fwConfigurationDB_RecipeManage.png' caption='Manage recipes panel'/>
</panel>

<panel name="fwConfigurationDB_RecipeApply.pnl" fname="fwConfigurationDB_RecipeApply" fullname="Apply recipe panel">
    <picture id="1" url='fwConfigurationDB_RecipeApply.png' caption=''/>
</panel>

<panel name="fwConfigurationDB_RecipeCreate.pnl" fname="fwConfigurationDB_RecipeCreate" fullname="Create recipe panel">
    <picture id="1" url='fwConfigurationDB_RecipeCreate.png' caption=''/>
</panel>

<panel name="fwConfigurationDB_RecipeEdit.pnl" fname="fwConfigurationDB_RecipeEdit" fullname="Edit recipe panel">
    <picture id="1" url='fwConfigurationDB_RecipeEdit.png' caption=''/>
</panel>

<panel name="fwConfigurationDB_RecipeAvanced.pnl" fname="fwConfigurationDB_RecipeAdvanced" fullname="Advanced recipe operations panel">
    <picture id="1" url='fwConfigurationDB_RecipeAdvanced.png' caption=''/>
</panel>

<panel name="fwConfigurationDB_DBConnectionEdit.pnl" fname="fwConfigurationDB_DBConnectionEdit" fullname="Edit DB Connection parameters panel">
    <picture id="1" url='fwConfigurationDB_DBConnectionEdit.png' caption=''/>
    <picture id="2" url='fwConfigurationDB_DBConnectionEdit_opts.png' caption='options'/>
    <picture id="3" url='fwConfigurationDB_DBConnectionEdit_OK.png' caption='Succesfull connection notification'/>
    <picture id="4" url='fwConfigurationDB_DBConnectionEdit_ERROR.png' caption='Connection failed notification'/>
</panel>

<panel name="fwConfigurationDB_CDBStatus.pnl" fname="fwConfigurationDB_CDBStatus" fullname="Status of ConfigurationDB connection">
    <picture id="1" url='fwConfigurationDB_CDBStatus.png' caption=''/>
</panel>

<panel name="fwConfigurationDB_ConfDBManager.pnl" fname="fwConfigurationDB_ConfDBManager" fullname="Advanced setup ans operations panel">
    <picture id="1" url='fwConfigurationDB_ConfDBManager.png' caption=''/>
</panel>

<panel name="fwConfigurationDB_ConfDBManager_DBConnections.pnl" fname="fwConfigurationDB_ConfDBManager_DBConnections" fullname="DB Connection management panel">
    <picture id="1" url='fwConfigurationDB_ConfDBManager_DBConnections.png' caption=''/>
</panel>

<panel name="fwConfigurationDB_ConfDBManager_RecipeCaches.pnl" fname="fwConfigurationDB_ConfDBManager_RecipeCaches" fullname="Recipe cache management panel">
    <picture id="1" url='fwConfigurationDB_ConfDBManager_RecipeCaches.png' caption=''/>
</panel>

<panel name="fwConfigurationDB_ConfDBManager_RecipeTypes.pnl" fname="fwConfigurationDB_ConfDBManager_RecipeTypes" fullname="Recipe type management panel">
    <picture id="1" url='fwConfigurationDB_ConfDBManager_RecipeTypes.png' caption=''/>
</panel>

<panel name="fwConfigurationDB_RecipeTypeEdit" fname="fwConfigurationDB_RecipeTypeEdit" fullname="Recipe type editor panel">
    <picture id="1" url='fwConfigurationDB_RecipeTypeEdit.png' caption=''/>
    <picture id="2" url='fwConfigurationDB_RecipeTypeEdit_2.png' caption=''/>
    <picture id="3" url='fwConfigurationDB_RecipeTypeEdit_3.png' caption=''/>
    <picture id="4" url='fwConfigurationDB_RecipeTypeEdit_4.png' caption=''/>
    <picture id="5" url='fwConfigurationDB_RecipeTypeEdit_Add.png' caption=''/>
</panel>

<panel name="fwConfigurationDB_RecipeSave_MissingRT.pnl" fname="fwConfigurationDB_RecipeSave_MissingRT" fullname="Handling of missing recipe type panel">
    <picture id="1" url='fwConfigurationDB_RecipeSave_MissingRT.png' caption=''/>
</panel>

<panel name="fwConfigurationDB_SelectionList.pnl" fname="fwConfigurationDB_SelectionList" fullname="Generic selection list panel">
    <picture id="1" url='fwConfigurationDB_SelectionList.png' caption='Panel used to select device types'/>
    <picture id="2" url='fwConfigurationDB_SelectionList-devices.png' caption='Panel used to select devices'/>
</panel>

<panel name="fwConfigurationDB_DBDeviceList.pnl" fname="fwConfigurationDB_DBDeviceList" fullname="List of devices stored in DB">
    <picture id="1" url='fwConfigurationDB_DBDeviceList.png' caption=''/>
</panel>

<panel name="fwConfigurationDB_DBBrowser.pnl" fname="fwConfigurationDB_DBBrowser" fullname="Database browser panel">
    <picture id="1" url='fwConfigurationDB_DBBrowser.png' caption=''/>
</panel>

<panel name="fwConfigurationDB_SqlQueryBrowser.pnl" fname="fwConfigurationDB_SqlQueryBrowser" fullname="Database SQL Query panel">
    <picture id="1" url='fwConfigurationDB_SqlQueryBrowser.png' caption=''/>
</panel>

<panel name="fwConfigurationDB_LoadDevicesFromDB.pnl" fname="fwConfigurationDB_LoadDevicesFromDB" fullname="Load devices from Database">
    <picture id="1" url='fwConfigurationDB_LoadDevicesFromDB.png' caption=''/>
</panel>

<panel name="fwConfigurationDB_SaveDevicesToDB.pnl" fname="fwConfigurationDB_SaveDevicesToDB" fullname="Save devices to Database">
    <picture id="1" url='fwConfigurationDB_SaveDevicesToDB.png' caption=''/>
</panel>

</component>

</components>