=== waqarphd/RPCDCS/JCOPfw/framework/framework5.0.1/PVSS/help/en_US.utf8/WebHelp/fwAccessControl/xml/FrameworkComponents.dtd
<?xml version="1.0" encoding="iso8859-1"?>

<!ELEMENT components ( (description)* | (component)*) >
<!ELEMENT description ANY>

<!ELEMENT component ( (panels) | (libraries) | (dependency)* |(description)?| (requirement)* )>
<!ATTLIST component
    name ID #REQUIRED
    desc CDATA #REQUIRED
>

<!ELEMENT panels ( (panel)? )>

<!ELEMENT panel ( (description)? | (link)? | (picture)? | (button)? | (dollarParam)? | (globalVar)? | (instruction)? | (restriction)? | (returns)? )>
<!ATTLIST panel
    name CDATA #REQUIRED
    fname CDATA #REQUIRED
    fullname CDATA #REQUIRED
    subdir CDATA #IMPLIED
>

<!ELEMENT dependency ANY>
<!ELEMENT requirement ANY>

<!ELEMENT returns ( (description)? |(df)? | (ds)? ) >
<!ELEMENT df ANY>
<!ATTLIST df
    idx CDATA #IMPLIED
    val CDATA #IMPLIED
>
<!ELEMENT ds ANY>
<!ATTLIST ds
    idx CDATA #IMPLIED
    val CDATA #IMPLIED
>

<!ELEMENT instruction ANY>
<!ATTLIST instruction
    action CDATA #REQUIRED
>


<!ELEMENT restriction ANY>
<!ATTLIST restriction
    id CDATA #IMPLIED
>


<!ELEMENT libraries ( (library)? )>

<!ELEMENT library ( (link)? )>
<!ATTLIST library
    name CDATA #REQUIRED
>

<!ELEMENT link ANY>
<!ATTLIST link
    url CDATA #REQUIRED
    text CDATA #REQUIRED
>

<!ELEMENT otherPanel ANY>
<!ATTLIST otherPanel
    name CDATA #REQUIRED
    component CDATA #IMPLIED
    text CDATA #IMPLIED
>


<!ELEMENT button ANY>
<!ATTLIST button
    name CDATA #IMPLIED
    img  CDATA #IMPLIED
    type (released|pressed) "released"
>

<!ELEMENT dollarParam ANY>
<!ATTLIST dollarParam
    name CDATA #REQUIRED
    scope (optional|required) "required"
>

<!ELEMENT globalVar ANY>
<!ATTLIST globalVar
    name CDATA #REQUIRED
    type CDATA #REQUIRED
>


<!ELEMENT picture ANY>
<!ATTLIST image
    id  CDATA #REQUIRED
    url CDATA #REQUIRED
    caption CDATA #IMPLIED
>

=== waqarphd/RPCDCS/JCOPfw/fwAccessControl/fwAccessControl_3_2_20/help/en_US.iso88591/fwAccessControl/xml/panels/fwAccessControl_PrivHoldersList.xml
<!DOCTYPE components SYSTEM "../FrameworkComponents.dtd">

<panel xmlns:html="http://www.w3.org/1999/xhtml" name="fwAccessControl_PrivHoldersList.pnl" 
    fname="fwAccessControl_PrivHoldersList" fullname="List of access right holders">
    <description> 
    <html:p>
    This panel allows to find the users (and groups) that are in possession of specific access right.
    In a typical scenario, a shift operator may need to find an expert.
    The panel is presented in Figure 1.
    <picture id="1" url='fwAccessControl_PrivHoldersList.png' caption='The list of access right holders'/>
    
    The panel allows to instantly access the detailed information about groups and users displayed in the list.
    Right clicking on one of the entries brings up a pop up window with description of the clicked group (Figure 2)
    or user (Figure 3).
    <picture id="3" url='fwAccessControl_PrivHoldersList_grp.png' caption='Pop-up window with description of a group'/>
    <picture id="3" url='fwAccessControl_PrivHoldersList_usr.png' caption='Pop-up window with description of a user'/>
    Double-clicking on the item, or choosing <button name="Commands>Show detail"/> in the popup brings up
    the panels with detailed information (<otherPanel name="fwAccessControl_EditGroup" text="Edit Group"/>
    or <otherPanel name="fwAccessControl_EditUser" text="Edit User"/> panels in read-only mode).
    </html:p>
    </description>
    
    <instruction action="To find the holders of a certain access right">
	You need to select the access right, by choosing Domain Name and Privilege Name in the selector lists.
	Once both are selected, the lists below will be filled with names of groups and users who are in possession
	of selected access right (i.e. selected privilege level in selected domain).
    </instruction>
    <instruction action="To get the details about a user or group">
	double-click the name in one of the tables, or right-click on it.
    </instruction>

    <restriction> The contents of this panel does not auto-update when domains, groups or users change
    </restriction>

    <restriction> Requesting the details of the user or group will not open separate window for every user
    (or group) - it will re-use the single UI module and update its content with every new selection.
    </restriction>

    <dollarParam name="domain" scope="optional"> The domain name which should be pre-set in the Domain selector </dollarParam>
    <dollarParam name="privilege" scope="optional"> The privilege name which should be pre-set in the Privilege selector </dollarParam>

</panel>
